{
    "name": "School Base",
    "version": "19.0.1.0.0",
    "summary": "Base module for School Management System",
    "description": "Foundation module for School Management System",
    "author": "Your Name",
    "category": "Education",
    "license": "LGPL-3",
    "depends": ["base", "mail", 'web'],
    "data": [
        "security/school_base_groups.xml",
        "security/school_record_rules.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        # dashboard views
        "views/admin_dashboard.xml",
        "views/teacher_dashboard.xml",
        "views/student_dashboard.xml",

        "views/school_class_subject_views.xml",
        "views/school_class_section_views.xml",
        "views/school_time_slot_views.xml",
        "views/school_weekly_day.xml",
        "views/school_class_views.xml",
        "views/school_student_views.xml",
        "views/school_student_enrollment_views.xml",
        "views/school_teacher_views.xml",
        "views/school_teacher_assignment_views.xml",
        "views/school_student_attendance_views.xml",
        "views/school_exam_type_views.xml",
        "views/school_exam_views.xml",
        "views/school_exam_time_slot_views.xml",
        "views/school_exam_result_views.xml",
        "views/school_grade_views.xml",
        "views/school_department_views.xml",
        "views/academic_year_views.xml",
        'reports/student_result_action.xml',
        'reports/student_result_report.xml',
        'reports/student_exam_routine_action.xml',
        "reports/student_exam_routine_report.xml",
        "reports/student_routine_action.xml",
        "reports/student_routine_report.xml",
        "views/school_base_menu.xml",
    ],
    "assets" :{
        'web.assets_backend' :[
            'school_base/static/src/js/*.js',
            'school_base/static/src/xml/*.xml',
            'school_base/static/src/css/*.css',
            'school_base/static/src/components/**/*.xml',
            'school_base/static/src/components/**/*.js',
            'school_base/static/src/components/**/*.css',
            'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css',

        ]
    },
    "installable": True,
    "application": True,
}