{
    "name": "School Base",
    "version": "19.0.1.0.0",
    "summary": "Base module for School Management System",
    "description": "Foundation module for School Management System",
    "author": "Your Name",
    "category": "Education",
    "license": "LGPL-3",
    "depends": ["base", "mail"],
    "data": [
        "security/school_base_groups.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/school_class_subject_views.xml",
        "views/school_class_section_views.xml",
        "views/school_class_views.xml",
        "views/school_student_views.xml",
        "views/school_teacher_views.xml",
        "views/school_department_views.xml",
        "views/academic_year_views.xml",
        "views/school_base_menu.xml",
    ],
    "installable": True,
    "application": True,
}