from . import school_base
from . import school_department
from . import school_teacher
from . import school_student
from . import school_academic
from . import school_attendance
from . import school_exam
from . import school_exam_result
from . import student_result_report
from . import student_exam_routine_report
from . import student_routine_report
from . import teacher_routine_report
from . import teacher_exam_routine_report
from . import school_tuition_fee